### PR TITLE
Fixed crash on unstable internet connection

### LINKED ISSUE #141: Need help handling socket timeout
I need help how to handle automatically this occasions. 
I would like to auto restart the application when this happens. 

## Expected Behavior
Restart after socket timeout.

## Actual Behavior
Application crash.

## Steps to Reproduce the Problem

  1. Internet outage.
  
## Specifications

  - Platform: Ubuntu 16
  - Version (can be found in package.json): v2.7.1
  - Node.js version (`node -v`): v9.7.1

## Error message

28-03 06:45:03.051: ERR!28-03 06:45:03.052:  listen Error: ESOCKETTIMEDOUT
ERR! listen     at ClientRequest.<anonymous> (/opt/miscord/node_modules/request/request.js:813:19)
ERR! listen     at Object.onceWrapper (events.js:219:13)
ERR! listen     at ClientRequest.emit (events.js:127:13)
ERR! listen     at ClientRequest.emit (domain.js:421:20)
ERR! listen     at TLSSocket.emitTimeout (_http_client.js:702:34)
ERR! listen     at Object.onceWrapper (events.js:219:13)
ERR! 28-03 06:45:03.052: listen     at TLSSocket.emit (events.js:127:13)
ERR! listen     at TLSSocket.emit (domain.js:421:20)
ERR! listen     at TLSSocket.Socket._onTimeout (net.js:419:8)
28-03 06:45:03.053: ERR! listen     at ontimeout (timers.js:466:11)
ERR!28-03 06:45:03.053:  listen     at tryOnTimeout (timers.js:304:5)
ERR! 28-03 06:45:03.053: listen     at Timer.listOnTimeout (timers.js:267:5)
ERR! listen28-03 06:45:03.053:   { Error: ESOCKETTIMEDOUT
ERR! listen     at ClientRequest.<anonymous> (/opt/miscord/node_modules/request/request.js:813:19)
28-03 06:45:03.053: ERR! listen     at Object.onceWrapper (events.js:219:13)
28-03 06:45:03.053: ERR! listen     at ClientRequest.emit (events.js:127:13)
28-03 06:45:03.054: ERR! listen     at ClientRequest.emit (domain.js:421:20)
28-03 06:45:03.054: ERR! listen     at TLSSocket.emitTimeout (_http_client.js:702:34)
ERR!28-03 06:45:03.054:  listen     at Object.onceWrapper (events.js:219:13)
ERR!28-03 06:45:03.054:  listen     at TLSSocket.emit (events.js:127:13)
ERR!28-03 06:45:03.054:  listen     at TLSSocket.emit (domain.js:421:20)
ERR! 28-03 06:45:03.054: listen     at TLSSocket.Socket._onTimeout (net.js:419:8)
ERR! 28-03 06:45:03.054: listen     at ontimeout (timers.js:466:11)
ERR!28-03 06:45:03.055:  listen     at tryOnTimeout (timers.js:304:5)
ERR!28-03 06:45:03.055:  listen     at Timer.listOnTimeout (timers.js:267:5)
ERR!28-03 06:45:03.055:  listen   cause: { Error: ESOCKETTIMEDOUT
ERR!28-03 06:45:03.055:  listen     at ClientRequest.<anonymous> (/opt/miscord/node_modules/request/request.js:813:19)
ERR! 28-03 06:45:03.055: listen     at Object.onceWrapper (events.js:219:13)
ERR! 28-03 06:45:03.055: listen     at ClientRequest.emit (events.js:127:13)
ERR! 28-03 06:45:03.055: listen     at ClientRequest.emit (domain.js:421:20)
ERR! 28-03 06:45:03.056: listen     at TLSSocket.emitTimeout (_http_client.js:702:34)
ERR!28-03 06:45:03.056:  listen     at Object.onceWrapper (events.js:219:13)
ERR!28-03 06:45:03.056:  listen     at TLSSocket.emit (events.js:127:13)
ERR!28-03 06:45:03.056:  listen     at TLSSocket.emit (domain.js:421:20)
ERR!28-03 06:45:03.056:  listen     at TLSSocket.Socket._onTimeout (net.js:419:8)
ERR!28-03 06:45:03.056:  listen     at ontimeout (timers.js:466:11)
ERR!28-03 06:45:03.056:  listen     at tryOnTimeout (timers.js:304:5)
ERR!28-03 06:45:03.056:  listen     at Timer.listOnTimeout (timers.js:267:5) code: 'ESOCKETTIMEDOUT', connect: false },
ERR!28-03 06:45:03.057:  listen   isOperational: true,
ERR!28-03 06:45:03.057:  listen   code: 'ESOCKETTIMEDOUT',
ERR!28-03 06:45:03.057:  listen   connect: false }
28-03 06:45:03.059: You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
TypeError: Cannot read property 'threadID' of undefined
    at module.exports.opts (/opt/miscord/lib/listeners/facebook.js:19:48)
    at config.facebook.client.listen (/opt/miscord/index.js:12:51)
    at /opt/miscord/node_modules/facebook-chat-api/src/listen.js:443:11
    at tryCatcher (/opt/miscord/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/opt/miscord/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/opt/miscord/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/opt/miscord/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/opt/miscord/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/opt/miscord/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/opt/miscord/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
    at process.topLevelDomainCallback (domain.js:101:23)

### PR DESCRIPTION
**Pull request by Bjornskjald**
Fixes #141... I hope. Someone test please
@mind12 @simeonlg

### CODE REVIEW

**Comment by mind12** [comment]
@Bjornskjald I will test this today and get back with the results.

**Comment by mind12** [comment]
@Bjornskjald 
Latest version crashed with the following errors. I reverted back to v2.7.1:

1|miscord  | 29-03 15:28:35.573: info
1|miscord  | 29-03 15:28:35.575:  
1|miscord  | 29-03 15:28:35.576: login Launching Miscord v2.7.3
1|miscord  | info
1|miscord  | 29-03 15:28:35.577:  login Logging in...
1|miscord  | 29-03 15:28:35.578: WARN
1|miscord  | 29-03 15:28:35.578:  
1|miscord  | 29-03 15:28:35.579: config.facebook.* is deprecated. Use config.messenger.* instead.
1|miscord  | 29-03 15:28:35.579:  
1|miscord  | 29-03 15:28:35.581: info
1|miscord  | 29-03 15:28:35.581:  
1|miscord  | 29-03 15:28:35.582: login
1|miscord  | 29-03 15:28:35.582:  Log level: info
1|miscord  | 29-03 15:28:35.582: info
1|miscord  | 29-03 15:28:35.583:  
1|miscord  | 29-03 15:28:35.583: updateNotifier
1|miscord  | 29-03 15:28:35.583:  Checking for updates...
1|miscord  | 29-03 15:28:36.142: info
1|miscord  | 29-03 15:28:36.143:  login
1|miscord  | 29-03 15:28:36.143:  Logging in to Discord...
1|miscord  | 29-03 15:28:40.033: info
1|miscord  | 29-03 15:28:40.033:  login Logged in to Discord
1|miscord  | 29-03 15:28:40.059: info
1|miscord  | 29-03 15:28:40.060:  login Got Discord channels list
1|miscord  | 29-03 15:28:40.061: ERR! 
1|miscord  | 29-03 15:28:40.062: error TypeError: Cannot read property 'forceLogin' of undefined
1|miscord  | 29-03 15:28:40.062: ERR! error     at Promise (/opt/miscord/lib/login/messenger.js:19:48)
1|miscord  | ERR! 
1|miscord  | 29-03 15:28:40.062: error     at new Promise (<anonymous>)
1|miscord  | ERR! 
1|miscord  | 29-03 15:28:40.063: error     at module.exports.config (/opt/miscord/lib/login/messenger.js:12:10)
1|miscord  | ERR!
1|miscord  | 29-03 15:28:40.063:  error     at getDiscord.then.discord (/opt/miscord/lib/login/login.js:21:12)
1|miscord  | 29-03 15:28:40.063: ERR! 
1|miscord  | 29-03 15:28:40.065: error     at <anonymous>
1|miscord  | ERR! error     at process._tickCallback (internal/process/next_tick.js:118:7)
1|miscord  | ERR! error  { TypeError: Cannot read property 'forceLogin' of undefined
1|miscord  | ERR! error     at Promise (/opt/miscord/lib/login/messenger.js:19:48)
1|miscord  | ERR! error     at new Promise (<anonymous>)
1|miscord  | ERR! error     at module.exports.config (/opt/miscord/lib/login/messenger.js:12:10)
1|miscord  | ERR! error     at getDiscord.then.discord (/opt/miscord/lib/login/login.js:21:12)
1|miscord  | ERR!
1|miscord  | 29-03 15:28:40.065:  error     at <anonymous>
1|miscord  | ERR!
1|miscord  | 29-03 15:28:40.067:  error     at process._tickCallback (internal/process/next_tick.js:118:7)
1|miscord  | ERR! error   stack: 'TypeError: Cannot read property \'forceLogin\' of undefined\n    at Promise (/opt/miscord/lib/login/messenger.js:19:48)\n    at new Promise (<anonymous>)\n    at module.exports.config (/opt/miscord/lib/login/messenger.js:12:10)\n    at getDiscord.then.discord (/opt/miscord/lib/login/login.js:21:12)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:118:7)' }

**Comment by Bjornskjald** [comment]
@mind12 Okay, I know why, it's a typo.

**Comment by Bjornskjald** [comment]
Fixed in #145, can you update and check now?

**Comment by mind12** [comment]
Much better now. 
However this warn remained but you mentioned somewhere you updated this code:
1|miscord  | 29-03 17:03:11.957: WARN29-03 17:03:11.957:  config.facebook.* is deprecated. Use config.messenger.* instead.

Enjoy your beer ;)
Zoltan Varga

**Comment by Bjornskjald** [comment]
I'm too young for beer, but thanks anyways 😃

**Pull request merged**
